# -*- coding: utf-8 -*-
"""embeddedML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wn4dUrWUVC45aMJoxDY5fiYbGfbxYAR
"""

!pip install tensorflow-model-optimization

pip install tf_keras

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_model_optimization as tfmot
import numpy as np

# 1. Hyperparameters & Setup
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 37 # Oxford-IIIT Pet dataset has 37 classes

# 2. Load and Preprocess Dataset
def preprocess_image(features):
    image = tf.image.resize(features['image'], (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0 # Normalize to [0, 1]
    label = features['label']
    return image, label

print("Loading dataset...")
(ds_train, ds_val), ds_info = tfds.load(
    'oxford_iiit_pet',
    split=['train', 'test'],
    with_info=True,
    as_supervised=False # Keep as dict to access 'image' and 'label'
)

train_dataset = ds_train.map(preprocess_image).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
val_dataset = ds_val.map(preprocess_image).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# 3. Build Base Model
print("Building MobileNetV3 Small...")
base_model = tf.keras.applications.MobileNetV3Small(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights='imagenet',
    pooling='avg'
)
base_model.trainable = True # Fine-tune the whole model

model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
])

def augment_image(image, label):
    # Randomly flip horizontally
    image = tf.image.random_flip_left_right(image)
    # Randomly adjust brightness and contrast
    image = tf.image.random_brightness(image, max_delta=0.2)
    image = tf.image.random_contrast(image, lower=0.8, upper=1.2)
    # Ensure values stay between [0, 1] after adjustments
    image = tf.clip_by_value(image, 0.0, 1.0)
    return image, label

# Apply augmentation ONLY to the training dataset
train_dataset = ds_train.map(preprocess_image) \
                        .map(augment_image) \
                        .batch(BATCH_SIZE) \
                        .prefetch(tf.data.AUTOTUNE)

# Validation stays the same (no augmentation)
val_dataset = ds_val.map(preprocess_image).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# 4. Apply Pruning
EPOCHS = 11
WARMUP_EPOCHS = 5
steps_per_epoch = np.ceil(ds_info.splits['train'].num_examples / BATCH_SIZE).astype(np.int32)

pruning_params = {
      'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(
          initial_sparsity=0.00, # Start at 0% to let weights stabilize
          final_sparsity=0.50,   # 50% is much safer for MobileNet
          begin_step=WARMUP_EPOCHS * steps_per_epoch, # Wait 5 epochs before pruning
          end_step=EPOCHS * steps_per_epoch
      )
}

print("Wrapping model for pruning...")

def apply_pruning(layer):
    if isinstance(layer, (tf.keras.layers.Dense, tf.keras.layers.Conv2D, tf.keras.layers.DepthwiseConv2D)):
        return tfmot.sparsity.keras.prune_low_magnitude(layer, **pruning_params)
    return layer

pruned_base_model = tf.keras.models.clone_model(
    base_model,
    clone_function=apply_pruning
)

pruned_model = tf.keras.Sequential([
    pruned_base_model,
    tfmot.sparsity.keras.prune_low_magnitude(
        tf.keras.layers.Dense(NUM_CLASSES, activation='softmax'),
        **pruning_params
    )
])

pruned_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Callbacks for pruning AND dynamic learning rate
callbacks = [
    tfmot.sparsity.keras.UpdatePruningStep(),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,      # Cut learning rate in half
        patience=3,      # If val_loss doesn't improve for 3 epochs
        min_lr=1e-6,
        verbose=1
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=8,
        restore_best_weights=True
    )
]

# 5. Train the Pruned Model
print("Training and pruning model...")
pruned_model.fit(train_dataset, validation_data=val_dataset, epochs=EPOCHS, callbacks=callbacks)

# 6. Strip Pruning Wrappers (Crucial step before saving/conversion)
print("Stripping pruning wrappers...")
model_for_export = tfmot.sparsity.keras.strip_pruning(pruned_model)

# 7. INT8 Quantization (Post-Training)
print("Quantizing to INT8...")
converter = tf.lite.TFLiteConverter.from_keras_model(model_for_export)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Representative dataset is required for full INT8 quantization
def representative_data_gen():
    for input_value, _ in train_dataset.take(100):
        yield [input_value]

converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # Input is INT8
converter.inference_output_type = tf.int8 # Output is INT8

tflite_quant_model = converter.convert()

# 8. Save the final model for the Raspberry Pi
with open('mobilenet_v3_pet_pruned_quantized.tflite', 'wb') as f:
    f.write(tflite_quant_model)

print("Success! Model saved as 'mobilenet_v3_pet_pruned_quantized.tflite'")

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_model_optimization as tfmot

# --- 1. Hyperparameters & Setup ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 37

# --- 2. Load and Preprocess Dataset ---
def preprocess_image(features):
    image = tf.image.resize(features['image'], (IMG_SIZE, IMG_SIZE))
    # MobileNetV2 expects float inputs in the range [-1.0, 1.0]
    image = (tf.cast(image, tf.float32) / 127.5) - 1.0
    label = features['label']
    return image, label

def augment_image(image, label):
    image = tf.image.random_flip_left_right(image)
    return image, label

print("Loading dataset...")
(ds_train, ds_val), ds_info = tfds.load(
    'oxford_iiit_pet',
    split=['train', 'test'],
    with_info=True,
    as_supervised=False
)

train_dataset = ds_train.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE) \
                        .map(augment_image, num_parallel_calls=tf.data.AUTOTUNE) \
                        .batch(BATCH_SIZE) \
                        .prefetch(tf.data.AUTOTUNE)

val_dataset = ds_val.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE) \
                    .batch(BATCH_SIZE) \
                    .prefetch(tf.data.AUTOTUNE)

# --- 3. Build MobileNetV2 ---
print("Building MobileNetV2...")
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights='imagenet',
    pooling='avg'
)
base_model.trainable = False

outputs = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(base_model.output)
model = tf.keras.Model(inputs=base_model.input, outputs=outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# --- 4. Train the Float Model ---
print("Training the classification head...")
model.fit(train_dataset, validation_data=val_dataset, epochs=5)

print("Unfreezing base model for fine-tuning...")
base_model.trainable = True
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

callbacks = [tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True)]
model.fit(train_dataset, validation_data=val_dataset, epochs=10, callbacks=callbacks)

# --- 5. Apply QAT (Natively Supported) ---
print("\nPreparing for Quantization-Aware Training (QAT)...")

# Because it's MobileNetV2, we can safely quantize the ENTIRE model.
# This ensures Batch Normalization layers are correctly folded into Conv2D layers.
qat_model = tfmot.quantization.keras.quantize_model(model)

qat_model.compile(
    # Use a low learning rate to gently calibrate the INT8 fake-quantization nodes
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Fine-tuning with QAT...")
# 2 epochs is usually enough to recover accuracy
qat_model.fit(train_dataset, validation_data=val_dataset, epochs=2)

# --- 6. INT8 Quantization ---
print("\nQuantizing to TFLite INT8...")
converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_data_gen():
    # Provide the [-1, 1] scaled images for accurate activation calibration
    for input_value, _ in train_dataset.unbatch().batch(1).take(300):
        yield [input_value]

converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_quant_model = converter.convert()

with open('mobilenet_v2_pet_qat.tflite', 'wb') as f:
    f.write(tflite_quant_model)

print("Success! QAT Model saved as 'mobilenet_v2_pet_qat.tflite'")

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
from tqdm import tqdm

# --- 1. Load the TFLite Model ---
model_path = "mobilenet_v2_pet_qat.tflite"

interpreter = tf.lite.Interpreter(
    model_path=model_path,
    experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_WITHOUT_DEFAULT_DELEGATES
)

interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]
output_details = interpreter.get_output_details()[0]

input_shape = input_details['shape']
input_dtype = input_details['dtype']

print(f"Model Expected Input Shape: {input_shape}")
print(f"Model Expected Input Dtype: {input_dtype}")

# --- 2. Load Oxford-IIIT Pet Dataset ---
dataset = tfds.load('oxford_iiit_pet', split='test', as_supervised=True)

# --- 3. Preprocessing Logic ---
def preprocess(image, label):
    # Resize
    image = tf.image.resize(image, (input_shape[1], input_shape[2]))

    # Base MobileNetV2 float scaling: map [0, 255] to [-1.0, 1.0]
    image = (tf.cast(image, tf.float32) / 127.5) - 1.0

    if input_dtype == np.int8:
        scale, zero_point = input_details['quantization']
        # Shift the [-1.0, 1.0] float image into the INT8 domain
        image = tf.round(image / scale) + zero_point
        image = tf.clip_by_value(image, -128, 127)
        image = tf.cast(image, tf.int8)

    return image, label

# --- 4. Run Inference ---
correct_predictions = 0
total_samples = 0

print("Running inference on the test set...")
for image, label in tqdm(dataset):
    processed_image, true_label = preprocess(image, label)
    input_data = tf.expand_dims(processed_image, axis=0)

    interpreter.set_tensor(input_details['index'], input_data)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details['index'])

    predicted_label = np.argmax(output_data)

    if predicted_label == true_label.numpy():
        correct_predictions += 1
    total_samples += 1

# --- 5. Results ---
accuracy = (correct_predictions / total_samples) * 100
print(f"\nFinal Test Accuracy: {accuracy:.2f}%")